/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoVisual;
import Proyecto.MainPro;
/**
 *
 * @author CHRONO
 */
public class Configuracion extends javax.swing.JPanel {
    public static int configuracion, dificultad, modo;

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
        
        grupoDificultad.add(dExperto);
        grupoDificultad.add(dMaestro); 
        grupoDificultad.add(dNormal);
        grupoModo.add(mAleatorio);
        grupoModo.add(mManual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDificultad = new javax.swing.ButtonGroup();
        grupoModo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dNormal = new javax.swing.JRadioButton();
        dExperto = new javax.swing.JRadioButton();
        dMaestro = new javax.swing.JRadioButton();
        mAleatorio = new javax.swing.JRadioButton();
        mManual = new javax.swing.JRadioButton();
        bt_back = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dificultad");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modo de Juego");

        dNormal.setSelected(true);
        dNormal.setText("Normal");
        dNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNormalActionPerformed(evt);
            }
        });

        dExperto.setText("Experto");
        dExperto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dExpertoActionPerformed(evt);
            }
        });

        dMaestro.setText("Maestro");
        dMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dMaestroActionPerformed(evt);
            }
        });

        mAleatorio.setSelected(true);
        mAleatorio.setText("Aleatorio");
        mAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAleatorioActionPerformed(evt);
            }
        });

        mManual.setText("Manual");
        mManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mManualActionPerformed(evt);
            }
        });

        bt_back.setText("Volver");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(dNormal)
                        .addGap(66, 66, 66)
                        .addComponent(dExperto)
                        .addGap(66, 66, 66)
                        .addComponent(dMaestro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(mAleatorio)
                        .addGap(120, 120, 120)
                        .addComponent(mManual)))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dExperto)
                    .addComponent(dMaestro)
                    .addComponent(dNormal))
                .addGap(80, 80, 80)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mAleatorio)
                    .addComponent(mManual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(bt_back)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dNormalActionPerformed

    private void dExpertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dExpertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dExpertoActionPerformed

    private void dMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dMaestroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dMaestroActionPerformed

    private void mAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAleatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mAleatorioActionPerformed

    private void mManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mManualActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // TODO add your handling code here:
        MainPro.inicio.Configuracion();
    }//GEN-LAST:event_bt_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    public static javax.swing.JRadioButton dExperto;
    public static javax.swing.JRadioButton dMaestro;
    public static javax.swing.JRadioButton dNormal;
    private javax.swing.ButtonGroup grupoDificultad;
    private javax.swing.ButtonGroup grupoModo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JRadioButton mAleatorio;
    public static javax.swing.JRadioButton mManual;
    // End of variables declaration//GEN-END:variables
}
